Cook branch1
DmitryRubtsov53/CookApp pull request #1
Opened 2022-12-19 11:05 UTC by DmitryRubtsov53

Прошу проверить ДЗ!

2022-12-21 13:51 UTC, OlgaLugacheva requested changes

2022-12-21 13:51 UTC, OlgaLugacheva commented on src/main/java/com/example/cookapp/controllers/CookAppController.java
> +    }
Все хорошо, но обычно принято разделять логику , так предполагалось, что будет контроллер рецептов и контроллер ингридиентов - давай разделим

2022-12-21 13:51 UTC, OlgaLugacheva commented on src/main/java/com/example/cookapp/service/CookAppService.java
> +    public Recipe addRecipe(Recipe recipe) {
касаемо сервиса - аналогично как с контроллерами - желательно сервис рецептов и сервис ингридиентов

2022-12-23 08:11 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +@RequestMapping("/ingredient")
ресурс в RequestMapping пишется во множественном числе, то есть ingredients

2022-12-23 08:12 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +    @PostMapping("/add")
Post - сам по себе говорит о добавлении ресурса, поэтому по правилам просто 
PostMapping (тогда в клиенте будет запрос POST localhost:8080/recipes

2022-12-23 08:13 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +    @GetMapping("/alling")
@GetMapping - просто гет звучит как получение всех, поэтому не нужно дополнительно писать метод

2022-12-23 08:13 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +    public Ingredient getTheIngredient(@PathVariable("num") Integer num) {
это правильно

2022-12-23 08:14 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +    @DeleteMapping("/del/{id}")
Delete - сам по себе удаляет, не нужно дополнительно писать чтобы он удалял
    @DeleteMapping("{id}")

2022-12-23 08:15 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +    @PutMapping("/edit/{id}")
@PutMapping("/edit/{id}")
пут - сам по себе говорит об изменении поэтому 
    @PutMapping("{id}")

2022-12-23 08:15 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +            return ResponseEntity.notFound().build();
возвращай измененный ингредиент, а не пустоту

2022-12-23 08:16 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +        return this.ingredientService.getTheIngredient(num);
проверка на то что есть должна быть, и если нет такого элемента  - ошибка

2022-12-23 08:17 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/CookAppController.java
> +@RequestMapping("/cookapp")
тут вроде как это рецепт, а вроде и нет :)
Но я бы поменял на recipes

2022-12-23 08:17 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/CookAppController.java
> +    @PostMapping("/creat")
все тоже самое что и в ингредиентах, надо делать по правилам REST-сервисов, не плодить лишние названия

2022-12-23 08:18 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/CookAppController.java
> +    @DeleteMapping("/del/{id}")
посмотри на ингредиенты, когда есть правила - не нужно думать об именах методов

2022-12-23 22:42 UTC, iStemmer commented on src/main/java/com/example/cookapp/model/Ingredient.java
> +//    public Ingredient(String ingredientName,  int count, String unit) {
если есть ломбок - то закоментированный код удалить

2022-12-23 22:43 UTC, iStemmer commented on src/main/java/com/example/cookapp/service/IngredientService.java
> +            return null;
лучше выкидывать ошибку здесь что такой не найден

2022-12-23 22:44 UTC, iStemmer commented on src/main/java/com/example/cookapp/service/IngredientService.java
> +public class IngredientService {
нужен интерфейс по критерию

2022-12-23 22:44 UTC, iStemmer commented on src/main/java/com/example/cookapp/service/RecipeService.java
> +public class RecipeService {
нужен интерфейс по критерию

2022-12-23 22:49 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/RecipeController.java
> +@RequestMapping("/recipe")
recipes

2022-12-24 08:10 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/IngregientController.java
> +    private final IngredientService ingredientService;
здесь должна быть зависимость от интерфейса

2022-12-24 08:11 UTC, iStemmer commented on src/main/java/com/example/cookapp/service/RecipeInterface.java
> +public interface RecipeInterface {
в java не добавляем слово Interface к классам и названиям файлов. 
Лучше придерживаться конвенции 
interface RecipeService
class RecipeServiceImpl/ RecipeMapService

2022-12-24 08:12 UTC, iStemmer commented on src/main/java/com/example/cookapp/controllers/RecipeController.java
> +    private final RecipeService recipeService;
внедряем интерфейс

2022-12-25 10:10 UTC, iStemmer commented on src/main/java/com/example/cookapp/service/IngredientServiceImpl.java
> +            throw new RuntimeException("Pецепта с таким id нет.");
throw new RuntimeException("Pецепта с таким id нет.");
Нужно переопределить свое исключение и выбрасывать его, + добавить ResponseStatus
можно вот тут подсмотреть в пункте 3
https://www.baeldung.com/spring-response-status

2022-12-26 09:49 UTC, merged